---
- name: Creating empty file using Ansible playbook
  hosts: all
  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
      path: "/tmp/test_ansible_file"
      state: touch
