---
- name: Playbook to test cloudforms embedded ansible
  hosts: all
  gather_facts: no 
  vars:
    package: 'httpd'
  tasks: 
    - name: Install package 
      yum:
        name: {{ package }}
        state: latest
...

