---
- name: Install Apache from an MSI 
  hosts: all 
 
  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: 'http://mirror.cc.columbia.edu/pub/software/wireshark/win32/Wireshark-win32-latest.msi'
        dest: 'C:\Users\Administrator\Downloads\Wireshark-win32-latest.msi'

    - name: Install MSI
      win_package: 
        path: 'C:\Users\Administrator\Downloads\Wireshark-win32-latest.msi'
        state: present
        
