---
- name: Run series of data gathering commands on the server
  hosts: localhost
  gather_facts: yes
  vars:
    ipaddress: 98.136.103.24
  tasks: 
    - name: run mtr against the alerted ip address for 5 second 
      shell: mtr -c5 "{{ ipaddress }}" > /tmp/output.txt
      async: 60
      poll: 0
      register: mtr_output
      ignore_error:
     
    - name: run ping for against the alerted ip address for 5 seconds
      shell: ping -c5 "{{ ipaddress }}"
      register: ping_output

    - name: run traceroute and capture output 
      shell: traceroute "{{ ipaddress  }}" 
      register: traceroute_output
     

...
