---
- name: Run series of data gathering commands on the server
  hosts: localhost
  gather_facts: yes
  vars:
  tasks: 
    - name: run mtr against the alerted ip address for 5 second 
      shell: mtr -c5 "{{ IP_LIST }}" > /tmp/output.txt
      async: 60
      poll: 0
      register: mtr_output
      ignore_error:
     
    - name: run ping for against the alerted ip address for 5 seconds
      shell: ping -c5 "{{ IP_LIST }}"
      register: ping_output

    - name: run traceroute and capture output 
      shell: traceroute "{{ IP_LIST  }}" 
      register: traceroute_output
     
     
    - name: send output to email address included in this
      mail:
        host: localhost
        port: 25
        to: surya.singh@in.ibm.com 
        cc: adahibha@in.ibm.com
        subject: Solarwind report 
        body: This is mtr output "{{mtr_output}}", this is ping output "{{ ping_output }}", this is traceroute output "{{ traceroute_output }}"


...
