---
- name: Run series of data gathering commands on the server
  hosts: localhost
  gather_facts: yes
  vars:
    ipaddress: 192.168.1.1
  tasks: 
    - name: run mtr against the alerted ip address for 5 second 
      shell: mtr -c5 "{{ ipaddress }}"
      register: mtr_output

    - name: run ping for against the alerted ip address for 5 seconds
      shell: ping -c5 "{{ ipaddress }}"
      register: ping_output

    - name: run traceroute and capture output 
      shell: traceroute "{{ ipaddress  }}" 
      regisrer: traceroute_output

...
